### ISSUE TITLE
compile project(':react-native-config') is not added to build.grade

### ISSUE THREAD

**Issue by yaronlevi** [zetachang/react-native-dotenv#17]
When calling react-native link, the line "compile project(':react-native-config')" is not added to the build.gradle file. This should be added or documented as a required manual step. Great Lib! Thanks (-:

**Comment by zetachang** [comment]
Hi, maybe you are creating issue in the wrong repo?

yaron <notifications@github.com> 於 2017年5月27日週六 下午9:30 寫道：
