### ISSUE TITLE
staging config

### ISSUE THREAD

**Issue by eddnav** [zetachang/react-native-dotenv#18]
Is there a way I can setup the environment manually? the dev/prod thing is not enough for me, I have some builds that are built as release (public betas) and I need to separate dev, staging and production.

**Comment by zetachang** [comment]
This might not be a great solution, but my suggestion is that you could keep different .env files and add a script to copy it to root folder based on different build environment.

**Comment by eddnav** [comment]
Sadly, I think the use case is a bit complex and scripts would not be the best option here... I tried using `react-native-config` and that adapted better to this use case, so I'll close this.
