### ISSUE TITLE
RN 0.46.0 packager fails

### ISSUE THREAD

**Issue by rmkpatchaa** [zetachang/react-native-dotenv#21]
Hi,

I've tried to update to RN 0.46.0 but build is broken as the packager folder doesn't exist (Replaced by Metro builder. (https://github.com/facebook/react-native/commit/236e9e4d01f60225855477b710fd4b5e1b8817fb)

**Comment by pdavid0** [comment]
#22  should resolve this

**Comment by rmkpatchaa** [comment]
Yup, Is it possible to use the pull request as source before the package is published ?

**Comment by zetachang** [comment]
@pdavid0 thanks for working on this, will release a new version later today.

**Comment by alizahid** [comment]
@zetachang When's the release coming?

**Comment by alizahid** [comment]
@pdavid0 I installed from `master`, and now I see this.

![simulator screen shot jul 9 2017 5 36 44 am](https://user-images.githubusercontent.com/941775/27990464-c89d3856-6468-11e7-85ed-7ac0ea6894e4.png)

**Comment by zetachang** [comment]
New version `v0.1.0` has been released. Please let me know if any you still encounter any issue 🙂
