### ISSUE TITLE
Variables are not updating

### ISSUE THREAD

**Issue by wachunei** [zetachang/react-native-dotenv#24]
Variables defined in `.env` are not updating.

I've tried:
1. Changing the file (add blank lines, whitspace)
1. Restarting the packager (`Ctrl + C; yarn start`)
1. 1 and 2 together
1. Running `react-native run-X` again
1. 3 and 4 together

😞 Don't know what else to try

**Comment by wachunei** [comment]
Figured it out: had to make any changes on the code too for it to update.

**Comment by josomers** [comment]
@wachunei running the packager with `--reset-cache` will do the trick as well.

**Comment by pencilcheck** [comment]
It seems like if you are using detached expo project you can also do this
`exp --tunnel --clear` that will remove cache on server starts

**Comment by ofaucorp** [comment]
@wachunei same trick works for me as well. i tried a lot of tries to fix but your approach fixed my issues.
thanks you very much.

**Comment by dominikznidar** [comment]
For me tests were not picking up changes in .env when calling `yarn test`. I resolved it by calling `yarn test --clearCache`.

**Comment by 6thpath** [comment]
> @wachunei running the packager with `--reset-cache` will do the trick as well.

where should i put --clear-cache

**Comment by jerodb** [comment]
--reset-cache worked for me.

@lPaths --reset-cache should be used when you start the React Native packager:
`$ node node_modules/react-native/local-cli/cli.js start --reset-cache`
or
`$ react-native start --reset-cache`

If you start it from your package.json scripts:
```
{
  ...
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  ...
}

$ yarn start --reset-cache
```

**Comment by Dsantacruz** [comment]
Manually edit the file importing react-native-dotenv by either adding an empty line or whitespace will work.

[https://www.npmjs.com/package/react-native-dotenv#faq](url)
