### ISSUE TITLE
Need variable value to be null/empty string in production env

### ISSUE THREAD

**Issue by LEEY19** [zetachang/react-native-dotenv#25]
@zetachang Hi David seeking your help, I have a variable which value needs to be set to null in production env. I can't put nothing as it will throw an error when I build the release mode. But if I put VARIABLE=null, it does not quite work like what I expected. Essentially, I need it to be an empty string under production env. How can I do that?

**Comment by Haroenv** [comment]
did you try `VARIABLE=''`

**Comment by jordanmkoncz** [comment]
I'm having the same problem.

@Haroenv I tried your suggestion and it doesn't seem to work, it causes the same error as if `VARIABLE` did not exist in the `.env` file at all.

**Comment by zetachang** [comment]
@jordanmkoncz thanks for pointing this out, it's a bug actually (at [this line](https://github.com/zetachang/react-native-dotenv/blob/master/babel-plugin-dotenv/index.js#L34), given that `!empty_string` is `true`, 😅 )

Will fix it soon and publish a new version.

**Comment by wachunei** [comment]
This is likely closed by #35

**Comment by zetachang** [comment]
The fix is released in v0.1.0, thank you guys for helping 💪
