### ISSUE TITLE
react-native 0.56.0 won't bundle

### ISSUE THREAD

**Issue by reed-jones** [zetachang/react-native-dotenv#44]
Although the build is successful, after upgrading to `react-native 0.56.0` and `babel-preset-react-native ^5.0.1` I get the error from Metro Bundler
```
Error: Cannot find module 'babel-preset-react-native-dotenv'
If you want to resolve "react-native-dotenv", use "module:react-native-dotenv"
```

**Comment by itsyogesh** [comment]
Having the same issue, I tried using `module:react-native-dotenv` but it shows another error. 
```
Error: Plugin/Preset files are not allowed to export objects, only functions.
```

**Comment by reed-jones** [comment]
I haven't tested, but looks like theres a PR with the fix https://github.com/zetachang/react-native-dotenv/pull/42

**Comment by zetachang** [comment]
Hi, v0.2.0 is released to address this 😄
