### ISSUE TITLE
Not Allowed To Export Objects

### ISSUE THREAD

**Issue by dbarks1024** [zetachang/react-native-dotenv#46]
I am still getting this error:  Error: Plugin/Preset files are not allowed to export objects, only functions.

**Comment by Nualiian** [comment]
@dbarks1024 what version of `react-native-dotenv` do you use?
I had the same issue, but when I upgraded to `0.2.0` as suggested [here in #44](https://github.com/zetachang/react-native-dotenv/issues/44), I no longer had that problem.

**Comment by dbarks1024** [comment]
Looks like its working for me now. Reinstalled it. Thanks!
