### ISSUE TITLE
Single import that populates process.env

### ISSUE THREAD

**Issue by stpch** [zetachang/react-native-dotenv#48]
First of all nice idea doing env variables with Babel / JS instead of native modules.

It would be great if a single `import 'react-native-dotenv';` populated `process.env` so that env variables could be accessed the regular `process.env.MY_VAR` way. Not sure if this is possible with the Babel approach.

**Comment by Moai-** [comment]
I agree. `import * as dotenv from 'react-native-dotenv'` results in an error. It would be really nice if we were able to import all, and then iterate through `dotenv` and assign it to `process.env` or whatever other global we want to use.

**Comment by cf-bosung90** [comment]
This will not work since assigning to process.env is done at runtime but you cannot control which code will be ran first, unless process.env is purely accessed at a later in time.
