### ISSUE TITLE
Import dotenv as default is not supported.

### ISSUE THREAD

**Issue by sibelius** [zetachang/react-native-dotenv#5]
`import config from 'react-native-dotenv'` does not work

I think it is a good to have to import all configs from .env file as the default export

**Comment by zetachang** [comment]
The safer option I have in mind for implementing this is to inlining the whole config object like below,

```js
import config from 'react-native-dotenv'
//become
const config = { API_KEY: 'foo', ...., OTHER_CONFIG: 'bar' } 
```

The drawback is that the config object literal will be duplicated in every file using it.

**Comment by sibelius** [comment]
good point

u should replace all `config.API_KEY`, but this could cause more problems later on

just keep it simple

**Comment by zetachang** [comment]
Yeah... but still glad you bring this up, and maybe there should be an error raised if user are importing env like this.
