### ISSUE TITLE
Suggestion - update README

### ISSUE THREAD

**Issue by sharoneh** [zetachang/react-native-dotenv#56]
Got an error like "Cannot read property 'bindings' of null..." when trying to add react-native-dotenv to a project.
Found out that in
```
{
  "presets": ["react-native", "react-native-dotenv"]
}

```
instead of "react-navite-dotenv" it should be "module:react-native-dotenv"
And instead of babel-preset-react-native it should be metro-react-native-babel-preset.

Please, update README to instruct for [metro-react-native-babel-preset](metro-react-native-babel-preset) instead of [babel-preset-react-native](https://www.npmjs.com/package/babel-preset-react-native#this-project-is-deprecated) as it is deprecated and it's been replaced by metro-react-native-babel-preset.

Hope this helps someone.

**Comment by zetachang** [comment]
Hi, thanks for pointing this out. I would love to merge the PR if you have
time to help 😃

Sharon <notifications@github.com> 於 2019年1月26日 週六 上午1:00 寫道：
